spring.application.name=job_management
spring.datasource.url=jdbc:postgresql://localhost:5432/job_management
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
security.token.secret=d2ea4c08358bd5860fd7244c7704c7e35fa904c328cba30d17b997d7f46ce58f
security.token.secret.candidate=d710df7affa25882871724845c03dc247041bd7dd1853db5302f492eabf961d2

spring.jpa.show-sql=true
